name: ci build  # 工作流名称

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu-cmake:
    name: ubuntu
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: |
       sudo apt-get update
       sudo apt-get install -y cmake g++ make libssl-dev libhiredis-dev
    - name: install workflow
      run: |
        git clone --depth 1 https://github.com/sogou/workflow.git
        cd workflow
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        sudo make install
    
    - name: cmake
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    
    - name: make
      run: make
      working-directory: ./build
