name: ci build  # 工作流名称

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu-cmake:
    name: ubuntu
    runs-on: ubuntu-latest 

    steps:
    - name: setup
      run: |
       sudo apt-get update
       sudo apt-get install -y cmake g++ make libssl-dev libworkflow-dev libhiredis-dev
    - uses: actions/checkout@v4
    - name: cmake
      run: |
        mkdir build && cd build && cmake ..
    - name: make
      run: make
      working-directory: ./build
